name: Skaled Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
#    inputs:
#      skaled_release:
#        description: 'Skaled Release'
#        default: 'develop-latest'
#        required: true

jobs:
  main_job:
    runs-on: ubuntu-latest
    env:
#      SKALED_RELEASE: ${{ github.event.inputs.skaled_release }}
      SKALED_RELEASE: develop-latest
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-venv nodejs jq btrfs-progs
        sudo npm install -g truffle
        sudo npm install -g yarn
        sudo chown -R runner:runner ~/.config   # HACK

    - name: Add secrets
      run: |
        touch ~/.netrc
        chmod 600 ~/.netrc
        echo "machine github.com" > ~/.netrc
        echo "login ${{ secrets.DIMALIT_ACCESS_TOKEN }}" >> ~/.netrc
        echo "password ${{ secrets.DIMALIT_ACCESS_TOKEN }}" >> ~/.netrc
        echo "${{ secrets.elvis_oregon_pem }}" > ~/elvis-oregon.pem

    - uses: docker-practice/actions-setup-docker@0.0.1
    
    - uses: hashicorp/setup-terraform@v1.1.0
      with:
        terraform_wrapper: false

    - uses: actions/checkout@v2

    - run: cd skaled_providers/endpoint_by_terraform_with_containers/tf/tf_scripts && terraform init

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Prepare SGX keys/certs
      run: |
        echo "${{ secrets.sgx_key }}" > sgx_certs/sgx.key
        chmod 600 sgx_certs/sgx.key
        sudo mkdir /skale_node_data
        sudo cp -r sgx_certs /skale_node_data

    - name: Update Environment
      run: |
        ./update_environment.sh skaled+internals
        ./update_environment.sh skaled+load_python
        ./update_environment.sh skaled+load_js
        ./update_environment.sh skaled+contractsRunningTest
        ./update_environment.sh skaled+filestorage

    - name: skaled+internals+pytest
      run: SKALED_PROVIDER=skaled_providers/binary_from_container ./run_tests.sh skaled+internals+pytest

    - name: skaled+internals+sktest_snapshot
      run: SKALED_PROVIDER=skaled_providers/binary_from_container ./run_tests.sh skaled+internals+sktest_snapshot

    - name: skaled+internals+test_node_rotation
      run: SKALED_PROVIDER=skaled_providers/binary_from_container ./run_tests.sh skaled+internals+test_node_rotation

    - name: skaled+contractsRunningTest+all
      run: SKALED_PROVIDER=skaled_providers/endpoint_by_container ./run_tests.sh skaled+contractsRunningTest+all

    - name: skaled+load_js+run_angry_cats
      run: SKALED_PROVIDER=skaled_providers/endpoint_by_container ./run_tests.sh skaled+load_js+run_angry_cats

    - name: skaled+load_python+all
      run: SKALED_PROVIDER=skaled_providers/binary_from_container ./run_tests.sh skaled+load_python+all

    - name: skaled+filestorage+all
      run: SKALED_PROVIDER=skaled_providers/endpoint_by_container ./run_tests.sh skaled+filestorage+all
