name: Skaled Manually-Running Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Test Suite'
        default: 'internals'
        required: false

      test:
        description: 'Test'
        default: 'pytest'
        required: false

      skaled_provider:
        description: 'Skaled Provider (binary_from_container|binary_as_artifact|container)'
        default: 'binary_from_container'
        required: true

      num_nodes:
        description: 'Num Nodes'
        default: '1'
        required: true

      skaled_release:
        description: 'Skaled Release'
        default: 'develop-latest'
        required: true

      kick_interval:
        description: 'KICK_INTERVAL (stability test)'
        default: '30'
        required: true

jobs:
  main_job:
    runs-on: ubuntu-18.04
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      PROJECT: skaled
      SUITE: ${{ github.event.inputs.suite }}
      TEST: ${{ github.event.inputs.test }}
      SKALED_PROVIDER: skaled_providers/${{ github.event.inputs.skaled_provider }}
      SKALED_RELEASE: ${{ github.event.inputs.skaled_release }}
      NUM_NODES: ${{ github.event.inputs.num_nodes }}
      DATA_DIR: /home/runner/data_dir
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NO_ULIMIT_CHECK: 1
      KICK_INTERVAL: ${{ github.event.inputs.kick_interval }}

    steps:

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip python3-venv jq btrfs-progs gnuplot
        sudo npm install -g truffle
        sudo npm install -g yarn
        sudo chown -R runner:runner ~/.config   # HACK

    - name: NODE 10.x
      run: |
        echo ------------ uninstall
        sudo apt-get remove nodejs || true
        echo ------------ force remove
        sudo rm -f /usr/local/bin/node || true
        sudo rm -f /usr/local/bin/npm || true
        sudo rm -f /usr/bin/node || true
        sudo rm -f /usr/bin/npm || true
        echo ------------ download
        curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        echo ------------ install
        sudo apt-get install nodejs
        echo ------------ node version check
        which node || echo "----> Looks like node was not installed, next command will fail"
        node --version
        echo ------------ npm version check
        which npm || echo "----> Looks like npm was not installed, next command will fail"
        npm --version

    - name: Add secrets
      run: |
        touch ~/.netrc
        chmod 600 ~/.netrc
        echo "machine github.com" > ~/.netrc
        echo "login ${{ secrets.DIMALIT_ACCESS_TOKEN }}" >> ~/.netrc
        echo "password ${{ secrets.DIMALIT_ACCESS_TOKEN }}" >> ~/.netrc
        echo "${{ secrets.elvis_oregon_pem }}" > ~/elvis-oregon.pem
        echo "${{ secrets.GRAFANA_CI_KEY }}" > ~/grafana_ci
        chmod 600 ~/grafana_ci

    - uses: docker-practice/actions-setup-docker@0.0.1
    
    - uses: hashicorp/setup-terraform@v1.1.0
      with:
        terraform_wrapper: false

    - uses: actions/checkout@v2

    - run: cd skaled_providers/endpoint_by_terraform_with_containers/tf/tf_scripts && terraform init

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Prepare SGX keys/certs
      run: |
        echo "${{ secrets.sgx_key }}" > sgx_certs/sgx.key
        chmod 600 sgx_certs/sgx.key
        sudo mkdir /skale_node_data
        sudo cp -r sgx_certs /skale_node_data
        sudo chown -R runner:runner /skale_node_data/sgx_certs/*
        wc /skale_node_data/sgx_certs/sgx.key

    - name: Update Environment
      run: |
        ./update_environment.sh $PROJECT+$SUITE

    - name: Run Tests
      run: |
        mkdir $DATA_DIR
        ./run_tests.sh $PROJECT+$SUITE+$TEST

    - uses: actions/upload-artifact@v2
      if: ${{ always() && env.SKALED_PROVIDER == 'skaled_providers/endpoint_by_terraform_with_containers' }}
      continue-on-error: true
      with:
        name: aws_config
        path: |
          skaled_providers/endpoint_by_terraform_with_containers/tf/output.json

    - name: Save logs
      if: ${{ always() && env.SKALED_PROVIDER == 'skaled_providers/endpoint_by_container' }}
      run: |
        sudo docker logs $(docker ps -a -q) 2>aleth.err 1>aleth.out || true
        sudo chown runner:runner aleth.*
      continue-on-error: true

    - uses: actions/upload-artifact@v2
      if: ${{ always() && env.SKALED_PROVIDER == 'skaled_providers/endpoint_by_container' }}
      continue-on-error: true
      with:
        path: |
          skaled_providers/endpoint_by_container/data_dir/config.json
          aleth.*

    - uses: actions/upload-artifact@v2
      if: ${{ always() && startsWith(env.SKALED_PROVIDER, 'skaled_providers/binary_') }}
      continue-on-error: true
      with:
        name: data_dir
        path: |
          ${{ env.DATA_DIR }}/**/aleth.*
          ${{ env.DATA_DIR }}/**/config.json
          
    - uses: actions/upload-artifact@v2
      if: ${{ always() && env.TEST == 'skaled_chart' }}
      continue-on-error: true
      with:
        name: skaled_chart
        path: |
          integration_tests/skaled/load_js/skaled_chart.png
          integration_tests/skaled/load_js/skaled_chart.txt
